# Generated by Django 5.0.4 on 2024-05-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='anwser',
            new_name='answer',
        ),
    ]
