# Generated by Django 5.0.4 on 2024-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_anwser_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_text',
            new_name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
