# Generated by Django 5.0.4 on 2024-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
