# Generated by Django 5.0.4 on 2024-04-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lecturer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='courses/default.jpg', null=True, upload_to='courses/'),
        ),
    ]
