# Generated by Django 5.0.4 on 2024-04-13 07:53

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
