# Generated by Django 5.0.4 on 2024-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_materialdetail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetail',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
