# Generated by Django 5.0.4 on 2024-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_assignment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
